Update release.yaml

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -117,7 +117,19 @@ jobs:
         run: |
           choco uninstall git --yes --force
           Remove-Item -Path "C:\Program Files\Git" -Recurse -Force -ErrorAction Ignore
+
+      - name: Add Git Bash to PATH
+        if: runner.os == 'Windows'
+        run: |
+          echo "C:\Program Files\Git\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
+          echo "C:\Program Files\Git\usr\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
           
+      - name: Verify Git Bash Installation
+        if: runner.os == 'Windows'
+        run: |
+          git --version
+          where sh || echo "sh still not found!"
+
       - name: Prepare Windows env
         if: runner.os == 'Windows'
         uses: matter-labs/era-compiler-ci/.github/actions/prepare-msys@v1
